// Design system: soft pearl-and-sage light theme
// Palette:
//   bg:         #f7f6f3  (warm parchment)
//   surface:    #ffffff
//   surface2:   #f2f1ee
//   border:     #e8e6e1
//   accent:     #3d8c6e  (sage green)
//   accentSoft: #e8f4ef
//   accentMid:  #6aad92
//   text:       #1c1c1e
//   textMid:    #6b6b72
//   textSoft:   #a8a8b0
//   danger:     #c0392b
//   warn:       #c07c28

export const S = {
  root: {
    minHeight: "100vh",
    background: "#f7f6f3",
    color: "#1c1c1e",
    fontFamily: "'DM Sans', 'Helvetica Neue', sans-serif",
    display: "flex",
    flexDirection: "column",
  },

  // ── Header ────────────────────────────────────────────────────────────────
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 36px",
    borderBottom: "1px solid #e8e6e1",
    background: "rgba(247,246,243,0.92)",
    backdropFilter: "blur(12px)",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  headerLeft: { display: "flex", alignItems: "center", gap: 20 },
  logoBtn: {
    display: "flex",
    alignItems: "baseline",
    gap: 2,
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 0,
  },
  logoA: {
    fontFamily: "'Playfair Display', Georgia, serif",
    fontSize: 24,
    fontWeight: 700,
    color: "#3d8c6e",
    letterSpacing: "-0.02em",
  },
  logoB: {
    fontFamily: "'Playfair Display', Georgia, serif",
    fontSize: 24,
    fontWeight: 400,
    color: "#1c1c1e",
    letterSpacing: "-0.02em",
  },
  logoTag: {
    fontSize: 9,
    letterSpacing: "0.22em",
    color: "#c0bdb5",
    marginLeft: 10,
    alignSelf: "center",
    textTransform: "uppercase",
  },
  navLinks: { display: "flex", gap: 4 },
  navLink: (active) => ({
    padding: "6px 14px",
    borderRadius: 20,
    background: active ? "#e8f4ef" : "none",
    border: `1px solid ${active ? "#c6e3d8" : "transparent"}`,
    color: active ? "#3d8c6e" : "#a8a8b0",
    fontSize: 13,
    fontWeight: 500,
    letterSpacing: "0.01em",
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.18s",
  }),
  headerRight: { display: "flex", alignItems: "center", gap: 12 },
  voiceBtn: (on) => ({
    padding: "7px 14px",
    background: on ? "#e8f4ef" : "#f2f1ee",
    border: `1px solid ${on ? "#b5d9ca" : "#e8e6e1"}`,
    borderRadius: 20,
    color: on ? "#3d8c6e" : "#a8a8b0",
    fontSize: 12,
    fontWeight: 500,
    letterSpacing: "0.04em",
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.18s",
  }),
  connWrap: { display: "flex", alignItems: "center", gap: 6 },
  dot: { width: 8, height: 8, borderRadius: "50%", transition: "all 0.3s" },
  connLabel: { fontSize: 11, letterSpacing: "0.1em", color: "#c0bdb5", textTransform: "uppercase" },

  // ── Landing ───────────────────────────────────────────────────────────────
  landingMain: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "72px 32px",
    gap: 48,
  },
  landingHero: { textAlign: "center", maxWidth: 560 },
  heroTitle: {
    fontFamily: "'Playfair Display', Georgia, serif",
    fontSize: "clamp(30px,5vw,54px)",
    fontWeight: 700,
    color: "#1c1c1e",
    lineHeight: 1.18,
    marginBottom: 16,
    letterSpacing: "-0.02em",
  },
  heroSub: {
    fontSize: 16,
    color: "#8a8a92",
    letterSpacing: "0.01em",
    lineHeight: 1.65,
  },
  landingCards: {
    display: "grid",
    gridTemplateColumns: "repeat(2,1fr)",
    gap: 20,
    maxWidth: 740,
    width: "100%",
  },
  landingCard: (accent) => ({
    background: "#ffffff",
    border: `1px solid #e8e6e1`,
    borderRadius: 20,
    padding: "36px 28px",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 14,
    textAlign: "center",
    transition: "all 0.22s",
    boxShadow: "0 2px 16px rgba(0,0,0,0.04)",
  }),
  landingCardIcon: { fontSize: 48, lineHeight: 1 },
  landingCardTitle: {
    fontFamily: "'Playfair Display', Georgia, serif",
    fontSize: 18,
    fontWeight: 700,
    color: "#1c1c1e",
    letterSpacing: "-0.01em",
  },
  landingCardDesc: { fontSize: 14, color: "#8a8a92", lineHeight: 1.65 },
  landingCardBtn: {
    marginTop: 8,
    padding: "10px 24px",
    borderRadius: 20,
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: "0.04em",
    border: "none",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  exPreviewRow: { display: "flex", gap: 10, flexWrap: "wrap", justifyContent: "center" },
  exPreviewChip: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "#f2f1ee",
    border: "1px solid #e8e6e1",
    borderRadius: 20,
    padding: "6px 16px",
    fontSize: 13,
    color: "#8a8a92",
  },
  landingFooter: { fontSize: 12, color: "#c0bdb5", letterSpacing: "0.08em" },

  // ── Tutorials ─────────────────────────────────────────────────────────────
  tutMain: { flex: 1, padding: "36px", maxWidth: 1100, margin: "0 auto", width: "100%" },
  tutPageHeader: { marginBottom: 28 },
  tutSubhead: { fontSize: 15, color: "#8a8a92", marginTop: 8, lineHeight: 1.65 },
  tutGrid: { display: "grid", gridTemplateColumns: "repeat(2,1fr)", gap: 20 },
  tutCard: {
    background: "#ffffff",
    border: "1px solid #e8e6e1",
    borderRadius: 16,
    padding: "28px",
    display: "flex",
    flexDirection: "column",
    gap: 18,
    boxShadow: "0 2px 12px rgba(0,0,0,0.04)",
  },
  tutCardTop: { display: "flex", alignItems: "center", gap: 16 },
  tutCardIcon: { fontSize: 40, lineHeight: 1 },
  tutCardName: {
    fontFamily: "'Playfair Display', Georgia, serif",
    fontSize: 17,
    fontWeight: 700,
    color: "#1c1c1e",
    marginBottom: 6,
    letterSpacing: "-0.01em",
  },
  diffBadge: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.14em",
    padding: "3px 10px",
    borderRadius: 20,
    border: "1px solid",
    textTransform: "uppercase",
  },
  tutTips: {
    background: "#f7f6f3",
    border: "1px solid #e8e6e1",
    borderRadius: 10,
    padding: "14px 16px",
  },
  tutTipsTitle: {
    fontSize: 10,
    letterSpacing: "0.2em",
    color: "#c0bdb5",
    marginBottom: 10,
    fontWeight: 700,
    textTransform: "uppercase",
  },
  tutTipRow: { display: "flex", alignItems: "flex-start", gap: 8, marginBottom: 7 },
  tutTipDot: { color: "#6aad92", fontSize: 11, marginTop: 3, flexShrink: 0 },
  tutTipTxt: { fontSize: 13, color: "#6b6b72", lineHeight: 1.5 },
  tutBtnRow: { display: "flex", flexDirection: "column", gap: 10, marginTop: "auto" },
  watchBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 16px",
    borderRadius: 10,
    background: "#fff5f5",
    border: "1px solid #f2cece",
    color: "#c0392b",
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: "0.04em",
    textDecoration: "none",
    transition: "all 0.18s",
  },
  channelTag: { fontSize: 10, color: "#e0b0b0", letterSpacing: "0.1em" },
  practiceBtn: {
    padding: "12px 16px",
    borderRadius: 10,
    background: "linear-gradient(135deg,#3d8c6e,#6aad92)",
    border: "none",
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: "0.06em",
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.18s",
    boxShadow: "0 2px 12px rgba(61,140,110,0.22)",
  },

  // ── Shared ────────────────────────────────────────────────────────────────
  sectionLabel: {
    fontSize: 11,
    letterSpacing: "0.2em",
    color: "#c0bdb5",
    marginBottom: 16,
    fontWeight: 700,
    textTransform: "uppercase",
  },
  errorBox: {
    margin: "20px auto",
    maxWidth: 700,
    background: "#fff5f5",
    border: "1px solid #f2cece",
    borderRadius: 12,
    padding: "16px 24px",
    color: "#c0392b",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 1.6,
  },

  // ── Workout ───────────────────────────────────────────────────────────────
  main: { flex: 1, padding: "28px 36px" },
  selectorWrap: { maxWidth: 900, margin: "0 auto" },
  grid: { display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 14, marginBottom: 28 },
  exCard: (active) => ({
    background: active ? "linear-gradient(145deg,#e8f4ef,#f0f9f5)" : "#ffffff",
    border: `1px solid ${active ? "#b5d9ca" : "#e8e6e1"}`,
    borderRadius: 14,
    padding: "24px 16px",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    transition: "all 0.22s",
    boxShadow: active
      ? "0 4px 20px rgba(61,140,110,0.12)"
      : "0 1px 6px rgba(0,0,0,0.04)",
  }),
  exIcon: { fontSize: 38, lineHeight: 1 },
  exName: { fontSize: 16, fontWeight: 600, color: "#1c1c1e", letterSpacing: "-0.01em" },
  exDesc: { fontSize: 11, color: "#a8a8b0", textAlign: "center", lineHeight: 1.45 },
  exCheck: {
    fontSize: 10,
    letterSpacing: "0.1em",
    color: "#3d8c6e",
    fontWeight: 700,
    background: "#e8f4ef",
    padding: "2px 8px",
    borderRadius: 10,
    border: "1px solid #c6e3d8",
    textTransform: "uppercase",
  },
  startBtn: (disabled) => ({
    width: "100%",
    padding: "18px 0",
    background: disabled
      ? "#f2f1ee"
      : "linear-gradient(135deg,#3d8c6e,#6aad92)",
    border: disabled ? "1px solid #e8e6e1" : "none",
    borderRadius: 12,
    color: disabled ? "#c0bdb5" : "#fff",
    fontSize: 15,
    fontWeight: 700,
    letterSpacing: "0.1em",
    cursor: disabled ? "not-allowed" : "pointer",
    fontFamily: "'Playfair Display', Georgia, serif",
    transition: "all 0.2s",
    boxShadow: disabled ? "none" : "0 4px 20px rgba(61,140,110,0.28)",
  }),
  session: {
    display: "grid",
    gridTemplateColumns: "1fr 380px",
    gap: 20,
    maxWidth: 1200,
    margin: "0 auto",
    alignItems: "start",
  },
  videoPanel: { display: "flex", flexDirection: "column", gap: 14 },
  videoBox: {
    position: "relative",
    borderRadius: 16,
    overflow: "hidden",
    border: "1px solid #e8e6e1",
    background: "#f2f1ee",
    aspectRatio: "4/3",
    boxShadow: "0 4px 24px rgba(0,0,0,0.08)",
  },
  videoEl: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  videoBadge: {
    position: "absolute",
    top: 12,
    left: 12,
    zIndex: 5,
    background: "rgba(255,255,255,0.88)",
    backdropFilter: "blur(8px)",
    padding: "5px 12px",
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "0.06em",
    color: "#1c1c1e",
    border: "1px solid #e8e6e1",
  },
  stagePill: (stage) => ({
    position: "absolute",
    top: 12,
    right: 12,
    zIndex: 5,
    padding: "5px 14px",
    borderRadius: 20,
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.08em",
    background:
      stage === "UP" || stage === "HOLD"
        ? "rgba(232,244,239,0.92)"
        : "rgba(255,245,230,0.92)",
    color:
      stage === "UP" || stage === "HOLD" ? "#3d8c6e" : "#c07c28",
    border: `1px solid ${
      stage === "UP" || stage === "HOLD" ? "#b5d9ca" : "#ecc990"
    }`,
    backdropFilter: "blur(6px)",
  }),
  depthWrap: {
    background: "#ffffff",
    border: "1px solid #e8e6e1",
    borderRadius: 12,
    padding: "16px 20px",
    boxShadow: "0 1px 6px rgba(0,0,0,0.04)",
  },
  depthRow: { display: "flex", justifyContent: "space-between", marginBottom: 10 },
  depthLbl: { fontSize: 11, letterSpacing: "0.16em", color: "#c0bdb5", fontWeight: 700, textTransform: "uppercase" },
  depthVal: (pct) => ({
    fontSize: 14,
    fontWeight: 700,
    color: pct > 70 ? "#3d8c6e" : pct > 40 ? "#c07c28" : "#c0392b",
    fontFamily: "'DM Mono', monospace",
  }),
  depthTrack: {
    height: 8,
    background: "#f2f1ee",
    borderRadius: 4,
    overflow: "visible",
    position: "relative",
  },
  depthFill: (pct) => ({
    height: "100%",
    borderRadius: 4,
    width: `${pct}%`,
    background:
      pct > 70
        ? "linear-gradient(90deg,#6aad92,#3d8c6e)"
        : pct > 40
        ? "linear-gradient(90deg,#e8b870,#c07c28)"
        : "linear-gradient(90deg,#e88070,#c0392b)",
    transition: "width 0.15s, background 0.3s",
    boxShadow: pct > 70 ? "0 0 6px rgba(61,140,110,0.3)" : "none",
  }),
  depthMarker: {
    position: "absolute",
    top: -3,
    left: "70%",
    width: 1.5,
    height: 14,
    background: "#c6e3d8",
    borderRadius: 1,
  },
  depthHints: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: 6,
    fontSize: 9,
    color: "#c0bdb5",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  statsPanel: { display: "flex", flexDirection: "column", gap: 14 },
  counterCard: {
    background: "#ffffff",
    border: "1px solid #e8e6e1",
    borderRadius: 14,
    padding: "24px",
    textAlign: "center",
    boxShadow: "0 2px 12px rgba(0,0,0,0.05)",
  },
  counterLbl: {
    fontSize: 11,
    letterSpacing: "0.18em",
    color: "#c0bdb5",
    fontWeight: 700,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  counterVal: {
    fontSize: 88,
    fontWeight: 700,
    color: "#3d8c6e",
    lineHeight: 1,
    fontFamily: "'Playfair Display', Georgia, serif",
    letterSpacing: "-0.04em",
    display: "block",
  },
  feedbackCard: {
    background: "#ffffff",
    border: "1px solid #e8e6e1",
    borderRadius: 14,
    padding: "20px",
    flex: 1,
    boxShadow: "0 2px 12px rgba(0,0,0,0.05)",
  },
  feedbackHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottom: "1px solid #f2f1ee",
  },
  feedbackTitle: { fontSize: 11, letterSpacing: "0.18em", color: "#c0bdb5", fontWeight: 700, textTransform: "uppercase" },
  voiceIndicator: (on) => ({
    fontSize: 10,
    letterSpacing: "0.1em",
    color: on ? "#3d8c6e" : "#c0bdb5",
    background: on ? "#e8f4ef" : "transparent",
    padding: "3px 8px",
    borderRadius: 6,
    border: `1px solid ${on ? "#c6e3d8" : "#e8e6e1"}`,
  }),
  feedbackList: { display: "flex", flexDirection: "column", gap: 10 },
  waitingRow: { display: "flex", alignItems: "center", gap: 10, padding: "8px 0" },
  waitingDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: "#e8e6e1",
    flexShrink: 0,
    animation: "pulse-dot 1.5s infinite",
  },
  waitingTxt: { fontSize: 13, color: "#c0bdb5", fontStyle: "italic" },
  fbRow: (isTop) => ({
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 10,
    background: isTop ? "#f7f6f3" : "transparent",
    border: isTop ? "1px solid #e8e6e1" : "1px solid transparent",
  }),
  fbIcon: (color) => ({
    width: 22,
    height: 22,
    borderRadius: 6,
    background: `${color}18`,
    border: `1px solid ${color}50`,
    color,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    fontWeight: 700,
    flexShrink: 0,
  }),
  fbMsg: { fontSize: 14, fontWeight: 500, letterSpacing: "0.01em", lineHeight: 1.45, color: "#3a3a40" },
  ctrlRow: { display: "flex", gap: 10 },
  resetBtn: {
    flex: 1,
    padding: "13px 0",
    background: "#f7f6f3",
    border: "1px solid #e8e6e1",
    borderRadius: 10,
    color: "#8a8a92",
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: "0.08em",
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.15s",
  },
  stopBtn: {
    flex: 1,
    padding: "13px 0",
    background: "#fff5f5",
    border: "1px solid #f2cece",
    borderRadius: 10,
    color: "#c0392b",
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: "0.08em",
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.15s",
  },

  // ── Authentication ─────────────────────────────────────────────────────────
  loginContainer: {
    maxWidth: 400,
    margin: "80px auto",
    padding: "44px 36px",
    background: "#ffffff",
    border: "1px solid #e8e6e1",
    borderRadius: 20,
    display: "flex",
    flexDirection: "column",
    gap: 18,
    textAlign: "center",
    boxShadow: "0 8px 40px rgba(0,0,0,0.07)",
  },
  input: {
    width: "100%",
    padding: "13px 16px",
    borderRadius: 10,
    background: "#f7f6f3",
    border: "1px solid #e8e6e1",
    color: "#1c1c1e",
    fontSize: 15,
    fontFamily: "inherit",
    boxSizing: "border-box",
    outline: "none",
    transition: "border-color 0.18s",
  },
  authBtn: {
    width: "100%",
    padding: "14px",
    borderRadius: 10,
    background: "linear-gradient(135deg,#3d8c6e,#6aad92)",
    border: "none",
    color: "#fff",
    fontWeight: 700,
    fontSize: 15,
    cursor: "pointer",
    letterSpacing: "0.06em",
    fontFamily: "inherit",
    boxShadow: "0 2px 14px rgba(61,140,110,0.24)",
    transition: "all 0.18s",
  },
  toggleText: {
    fontSize: 13,
    color: "#a8a8b0",
    cursor: "pointer",
    textDecoration: "underline",
    textDecorationColor: "#d8d6d0",
  },
  logoutBtn: {
    background: "transparent",
    border: "1px solid #f2cece",
    color: "#c0392b",
    padding: "6px 14px",
    borderRadius: 20,
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 600,
    transition: "all 0.15s",
  },
  loginNavBtn: {
    background: "linear-gradient(135deg,#3d8c6e,#6aad92)",
    border: "none",
    color: "#fff",
    padding: "6px 14px",
    borderRadius: 20,
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 600,
    boxShadow: "0 1px 8px rgba(61,140,110,0.22)",
    transition: "all 0.15s",
  },

  // ── Dashboard ─────────────────────────────────────────────────────────────
  dashboard: { maxWidth: 1000, margin: "0 auto", padding: "40px", flex: 1, width: "100%" },
  statsGrid: { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 18, marginBottom: 40 },
  quickStart: { marginBottom: 40 },
  exerciseButtons: { display: "flex", gap: 14 },
  recentSection: { marginBottom: 40 },
  sessionCard: {
    background: "#ffffff",
    border: "1px solid #e8e6e1",
    borderRadius: 12,
    padding: "18px 22px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
    cursor: "pointer",
    boxShadow: "0 1px 6px rgba(0,0,0,0.04)",
    transition: "box-shadow 0.18s, border-color 0.18s",
  },
  sessionCardLeft: { display: "flex", flexDirection: "column", gap: 4 },
  sessionTitle: { color: "#1c1c1e", fontSize: 17, fontWeight: 600, letterSpacing: "-0.01em" },
  sessionMeta: { color: "#a8a8b0", fontSize: 13 },
  sessionBadge: {
    background: "#e8f4ef",
    color: "#3d8c6e",
    padding: "4px 10px",
    borderRadius: 20,
    fontSize: 12,
    fontWeight: 700,
    border: "1px solid #c6e3d8",
    letterSpacing: "0.04em",
  },

  // ── Reports ───────────────────────────────────────────────────────────────
  reportsPage: { maxWidth: 1000, margin: "0 auto", padding: "40px", flex: 1, width: "100%" },
  timeSelector: { display: "flex", gap: 8, marginBottom: 30 },
  timeBtn: (active) => ({
    background: active ? "#3d8c6e" : "transparent",
    color: active ? "#fff" : "#8a8a92",
    border: `1px solid ${active ? "#3d8c6e" : "#e8e6e1"}`,
    padding: "7px 18px",
    borderRadius: 20,
    cursor: "pointer",
    fontWeight: 600,
    fontSize: 13,
    fontFamily: "inherit",
    transition: "all 0.18s",
  }),
  chartCard: {
    background: "#ffffff",
    border: "1px solid #e8e6e1",
    borderRadius: 16,
    padding: "28px 30px",
    marginBottom: 24,
    boxShadow: "0 2px 12px rgba(0,0,0,0.04)",
  },
  chartTitle: {
    color: "#1c1c1e",
    fontSize: 18,
    marginBottom: 20,
    fontWeight: 600,
    letterSpacing: "-0.01em",
    fontFamily: "'Playfair Display', Georgia, serif",
  },
  chartRow: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 30 },
  statItems: { display: "flex", flexDirection: "column", gap: 14 },
  statItem: {
    display: "flex",
    justifyContent: "space-between",
    padding: "10px 0",
    borderBottom: "1px solid #f2f1ee",
  },
  statLabel: { color: "#a8a8b0", fontSize: 14 },
  statVal: { color: "#1c1c1e", fontSize: 17, fontWeight: 600, letterSpacing: "-0.01em" },
};