export const S = {
  root: {
    minHeight:"100vh", background:"#07070f",
    color:"#e0e0e0", fontFamily:"'Rajdhani',sans-serif",
    display:"flex", flexDirection:"column",
  },

  // ── Header ────────────────────────────────────────────────────────────────
  header: {
    display:"flex", alignItems:"center", justifyContent:"space-between",
    padding:"14px 32px",
    borderBottom:"1px solid #12121e",
    background:"linear-gradient(90deg,#0a0a18,#0d0d20)",
    position:"sticky", top:0, zIndex:100,
  },
  headerLeft: { display:"flex", alignItems:"center", gap:20 },
  logoBtn: {
    display:"flex", alignItems:"baseline", gap:2,
    background:"none", border:"none", cursor:"pointer", padding:0,
  },
  logoA: { fontFamily:"'Orbitron',sans-serif", fontSize:26, fontWeight:900, color:"#00e676", letterSpacing:"0.08em" },
  logoB: { fontFamily:"'Orbitron',sans-serif", fontSize:26, fontWeight:700, color:"#ffffff", letterSpacing:"0.08em" },
  logoTag: { fontSize:9, letterSpacing:"0.18em", color:"#444", marginLeft:10, alignSelf:"center" },
  navLinks: { display:"flex", gap:6 },
  navLink: (active) => ({
    padding:"6px 14px", borderRadius:8,
    background: active ? "#00e67614" : "none",
    border: `1px solid ${active ? "#00e67640" : "transparent"}`,
    color: active ? "#00e676" : "#555",
    fontSize:12, fontWeight:700, letterSpacing:"0.12em",
    cursor:"pointer", fontFamily:"inherit", transition:"all 0.2s",
  }),
  headerRight: { display:"flex", alignItems:"center", gap:14 },
  voiceBtn: (on) => ({
    padding:"7px 14px",
    background: on ? "#0d2818" : "#1a1a1a",
    border:`1px solid ${on ? "#00e676" : "#333"}`,
    borderRadius:8, color: on ? "#00e676" : "#666",
    fontSize:12, fontWeight:700, letterSpacing:"0.1em",
    cursor:"pointer", fontFamily:"inherit", transition:"all 0.2s",
  }),
  connWrap: { display:"flex", alignItems:"center", gap:6 },
  dot: { width:9, height:9, borderRadius:"50%", transition:"all 0.3s" },
  connLabel: { fontSize:10, letterSpacing:"0.15em", color:"#555" },

  // ── Landing ─────────────────────────────────────────────────────────────
  landingMain: {
    flex:1, display:"flex", flexDirection:"column",
    alignItems:"center", justifyContent:"center",
    padding:"60px 32px", gap:40,
  },
  landingHero: { textAlign:"center", maxWidth:600 },
  heroTitle: {
    fontFamily:"'Orbitron',sans-serif",
    fontSize:"clamp(28px,5vw,52px)", fontWeight:900,
    color:"#fff", lineHeight:1.15, marginBottom:16, letterSpacing:"0.04em",
  },
  heroSub: { fontSize:18, color:"#777", letterSpacing:"0.08em" },
  landingCards: {
    display:"grid", gridTemplateColumns:"repeat(2,1fr)",
    gap:20, maxWidth:740, width:"100%",
  },
  landingCard: (accent) => ({
    background:"linear-gradient(145deg,#0e0e1a,#111120)",
    border:`1px solid ${accent}40`,
    borderRadius:20, padding:"36px 28px",
    cursor:"pointer", display:"flex", flexDirection:"column",
    alignItems:"center", gap:14, textAlign:"center",
    transition:"all 0.25s", boxShadow:`0 4px 32px ${accent}18`,
  }),
  landingCardIcon:  { fontSize:52, lineHeight:1 },
  landingCardTitle: { fontFamily:"'Orbitron',sans-serif", fontSize:18, fontWeight:900, color:"#fff", letterSpacing:"0.1em" },
  landingCardDesc:  { fontSize:15, color:"#888", lineHeight:1.6 },
  landingCardBtn: {
    marginTop:8, padding:"10px 24px", borderRadius:30,
    fontSize:13, fontWeight:800, letterSpacing:"0.14em",
    border:"none", cursor:"pointer", fontFamily:"'Orbitron',sans-serif",
  },
  exPreviewRow: { display:"flex", gap:12, flexWrap:"wrap", justifyContent:"center" },
  exPreviewChip: {
    display:"flex", alignItems:"center", gap:6,
    background:"#0e0e1a", border:"1px solid #2a2a3e",
    borderRadius:30, padding:"8px 18px", fontSize:14, color:"#777",
  },
  landingFooter: { fontSize:13, color:"#444", letterSpacing:"0.12em" },

  // ── Tutorials ─────────────────────────────────────────────────────────────
  tutMain: { flex:1, padding:"32px", maxWidth:1100, margin:"0 auto", width:"100%" },
  tutPageHeader: { marginBottom:28 },
  tutSubhead: { fontSize:16, color:"#777", marginTop:8, lineHeight:1.6 },
  tutGrid: { display:"grid", gridTemplateColumns:"repeat(2,1fr)", gap:20 },
  tutCard: {
    background:"linear-gradient(145deg,#0e0e1a,#111120)",
    border:"1px solid #2a2a3e", borderRadius:16,
    padding:"28px", display:"flex", flexDirection:"column", gap:18,
    boxShadow:"inset 0 1px 0 #ffffff08",
  },
  tutCardTop:  { display:"flex", alignItems:"center", gap:16 },
  tutCardIcon: { fontSize:48, lineHeight:1 },
  tutCardName: { fontFamily:"'Orbitron',sans-serif", fontSize:18, fontWeight:900, color:"#fff", marginBottom:6 },
  diffBadge: { fontSize:11, fontWeight:800, letterSpacing:"0.14em", padding:"4px 12px", borderRadius:20, border:"1px solid" },
  tutTips: { background:"#ffffff06", border:"1px solid #2a2a3e", borderRadius:10, padding:"16px 18px" },
  tutTipsTitle: { fontSize:11, letterSpacing:"0.18em", color:"#666", marginBottom:10, fontWeight:700 },
  tutTipRow:   { display:"flex", alignItems:"flex-start", gap:10, marginBottom:8 },
  tutTipDot:   { color:"#00e676", fontSize:14, marginTop:2, flexShrink:0 },
  tutTipTxt:   { fontSize:14, color:"#ccc", lineHeight:1.4 },
  tutBtnRow:   { display:"flex", flexDirection:"column", gap:10, marginTop:"auto" },
  watchBtn: {
    display:"flex", alignItems:"center", justifyContent:"space-between",
    padding:"14px 18px", borderRadius:10,
    background:"#ff000015", border:"1px solid #ff000060",
    color:"#ff5555", fontSize:14, fontWeight:700, letterSpacing:"0.08em",
    textDecoration:"none", transition:"all 0.2s",
  },
  channelTag:  { fontSize:11, color:"#ff4444aa", letterSpacing:"0.1em" },
  practiceBtn: {
    padding:"14px 18px", borderRadius:10,
    background:"linear-gradient(90deg,#00e676,#00bfa5)",
    border:"none", color:"#000",
    fontSize:14, fontWeight:800, letterSpacing:"0.1em",
    cursor:"pointer", fontFamily:"inherit", transition:"all 0.2s",
  },

  // ── Shared ────────────────────────────────────────────────────────────────
  sectionLabel: { fontSize:14, letterSpacing:"0.22em", color:"#666", marginBottom:16, fontWeight:700 },
  errorBox: {
    margin:"20px auto", maxWidth:700,
    background:"#1a0505", border:"1px solid #ff174450",
    borderRadius:12, padding:"16px 24px",
    color:"#ff6659", fontSize:14, textAlign:"center", lineHeight:1.6,
  },

  // ── Workout ───────────────────────────────────────────────────────────────
  main: { flex:1, padding:"28px 32px" },
  selectorWrap: { maxWidth:1200, margin:"0 auto" },
  grid: { display:"grid", gridTemplateColumns:"repeat(2,1fr)", gap:18, marginBottom:28 },
  exCard: (active) => ({
    background: active ? "linear-gradient(145deg,#0d2818,#0a1f12)" : "linear-gradient(145deg,#0e0e1a,#111120)",
    border:`1px solid ${active ? "#00e676" : "#2a2a3e"}`,
    borderRadius:16, padding:"32px 24px", cursor:"pointer",
    display:"flex", flexDirection:"column", alignItems:"center", gap:12,
    transition:"all 0.25s",
    boxShadow: active ? "0 0 24px #00e67624,inset 0 1px 0 #00e67622" : "inset 0 1px 0 #ffffff08",
  }),
  exIcon:  { fontSize:52, lineHeight:1 },
  exName:  { fontSize:19, fontWeight:700, color:"#fff", letterSpacing:"0.06em" },
  exDesc:  { fontSize:12, color:"#777", textAlign:"center" },
  exCheck: { fontSize:11, letterSpacing:"0.12em", color:"#00e676", fontWeight:700, background:"#00e67618", padding:"4px 10px", borderRadius:10, border:"1px solid #00e67640" },
  exHelpLink: { fontSize:12, color:"#9e9eff", textDecoration:"none", marginTop:6, letterSpacing:"0.08em", fontWeight:600 },
  startBtn: (disabled) => ({
    width:"100%", padding:"18px 0",
    background: disabled ? "#111118" : "linear-gradient(90deg,#00e676,#00bfa5)",
    border: disabled ? "1px solid #2a2a3e" : "none",
    borderRadius:12, color: disabled ? "#444" : "#000",
    fontSize:17, fontWeight:800, letterSpacing:"0.18em",
    cursor: disabled ? "not-allowed" : "pointer",
    fontFamily:"'Orbitron',sans-serif", transition:"all 0.2s",
    boxShadow: disabled ? "none" : "0 4px 24px #00e67630",
  }),
  session: {
    display:"grid", gridTemplateColumns:"1fr 400px",
    gap:24, maxWidth:1300, margin:"0 auto", alignItems:"start",
  },
  videoPanel: { display:"flex", flexDirection:"column", gap:14 },
  videoBox: {
    position:"relative", borderRadius:16, overflow:"hidden",
    border:"1px solid #2a2a3e", background:"#050508",
    aspectRatio:"4/3", boxShadow:"0 8px 32px #00000060",
  },
  videoEl: { position:"absolute", top:0, left:0, width:"100%", height:"100%", objectFit:"cover", display:"block" },
  videoBadge: {
    position:"absolute", top:14, left:14, zIndex:5,
    background:"#000000cc", padding:"6px 14px", borderRadius:8,
    fontSize:13, fontWeight:700, letterSpacing:"0.12em", color:"#fff", border:"1px solid #ffffff18",
  },
  stagePill: (stage) => ({
    position:"absolute", top:14, right:14, zIndex:5,
    padding:"6px 16px", borderRadius:20,
    fontSize:14, fontWeight:800, letterSpacing:"0.1em",
    background:(stage==="UP"||stage==="HOLD") ? "#00e67622" : "#ff910022",
    color:(stage==="UP"||stage==="HOLD") ? "#00e676" : "#ff9100",
    border:`1px solid ${(stage==="UP"||stage==="HOLD") ? "#00e67660" : "#ff910060"}`,
  }),
  depthWrap: { background:"#0e0e1a", border:"1px solid #2a2a3e", borderRadius:12, padding:"18px 22px" },
  depthRow:  { display:"flex", justifyContent:"space-between", marginBottom:10 },
  depthLbl:  { fontSize:12, letterSpacing:"0.2em", color:"#777", fontWeight:700 },
  depthVal: (pct) => ({ fontSize:16, fontWeight:800, color:pct>70?"#00e676":pct>40?"#ff9100":"#ff1744", fontFamily:"'Orbitron',sans-serif" }),
  depthTrack: { height:14, background:"#1a1a2e", borderRadius:6, overflow:"visible", position:"relative" },
  depthFill: (pct) => ({
    height:"100%", borderRadius:6, width:`${pct}%`,
    background: pct>70 ? "linear-gradient(90deg,#00bfa5,#00e676)" : pct>40 ? "linear-gradient(90deg,#ff6d00,#ff9100)" : "linear-gradient(90deg,#b71c1c,#ff1744)",
    transition:"width 0.15s,background 0.3s",
    boxShadow: pct>70 ? "0 0 8px #00e67660" : "none",
  }),
  depthMarker: { position:"absolute", top:-3, left:"70%", width:2, height:18, background:"#00e67640", borderRadius:1 },
  depthHints: { display:"flex", justifyContent:"space-between", marginTop:6, fontSize:10, color:"#555", letterSpacing:"0.1em" },
  statsPanel: { display:"flex", flexDirection:"column", gap:14 },
  counterCard: {
    background:"linear-gradient(145deg,#0e0e1a,#111120)",
    border:"1px solid #2a2a3e", borderRadius:16, padding:"28px", textAlign:"center",
    boxShadow:"inset 0 1px 0 #ffffff08",
  },
  counterLbl: { fontSize:12, letterSpacing:"0.2em", color:"#777", fontWeight:700, marginBottom:8 },
  counterVal: { fontSize:108, fontWeight:900, color:"#00e676", lineHeight:1, fontFamily:"'Orbitron',sans-serif", textShadow:"0 0 32px #00e67644", display:"block" },
  feedbackCard: {
    background:"linear-gradient(145deg,#0e0e1a,#111120)",
    border:"1px solid #2a2a3e", borderRadius:16, padding:"24px", flex:1,
    boxShadow:"inset 0 1px 0 #ffffff08",
  },
  feedbackHeader: { display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:16, paddingBottom:12, borderBottom:"1px solid #2a2a3e" },
  feedbackTitle: { fontSize:13, letterSpacing:"0.18em", color:"#888", fontWeight:700 },
  voiceIndicator: (on) => ({ fontSize:11, letterSpacing:"0.12em", color:on?"#00e676":"#666", background:on?"#00e67618":"transparent", padding:"4px 10px", borderRadius:6, border:`1px solid ${on?"#00e67640":"#333"}` }),
  feedbackList: { display:"flex", flexDirection:"column", gap:10 },
  waitingRow: { display:"flex", alignItems:"center", gap:10, padding:"8px 0" },
  waitingDot: { width:10, height:10, borderRadius:"50%", background:"#444", flexShrink:0, animation:"pulse-dot 1.5s infinite" },
  waitingTxt: { fontSize:15, color:"#555", fontStyle:"italic" },
  fbRow: (isTop) => ({ display:"flex", alignItems:"flex-start", gap:12, padding:"12px 14px", borderRadius:10, background:isTop?"#ffffff08":"transparent", border:isTop?"1px solid #ffffff12":"1px solid transparent" }),
  fbIcon: (color) => ({ width:26, height:26, borderRadius:6, background:`${color}20`, border:`1px solid ${color}50`, color, display:"flex", alignItems:"center", justifyContent:"center", fontSize:14, fontWeight:900, flexShrink:0 }),
  fbMsg: { fontSize:15, fontWeight:600, letterSpacing:"0.02em", lineHeight:1.4 },
  ctrlRow: { display:"flex", gap:10 },
  resetBtn: { flex:1, padding:"16px 0", background:"#0e0e1a", border:"1px solid #2a2a3e", borderRadius:10, color:"#999", fontSize:14, fontWeight:800, letterSpacing:"0.14em", cursor:"pointer", fontFamily:"'Rajdhani',sans-serif" },
  stopBtn:  { flex:1, padding:"16px 0", background:"#1a0505", border:"1px solid #ff1744", borderRadius:10, color:"#ff1744", fontSize:14, fontWeight:800, letterSpacing:"0.14em", cursor:"pointer", fontFamily:"'Rajdhani',sans-serif", boxShadow:"0 0 12px #ff174420" },

  // Recording UI
  recordingCard: {
    background:"linear-gradient(145deg,#0e0e1a,#111120)",
    border:"1px solid #2a2a3e", borderRadius:16, padding:"22px",
    boxShadow:"inset 0 1px 0 #ffffff08",
  },
  recordingHeader: { marginBottom:14 },
  recordingTitle: { fontSize:13, letterSpacing:"0.18em", color:"#888", fontWeight:700 },
  repLimitRow: { display:"flex", alignItems:"center", gap:10, marginBottom:14 },
  repLimitLabel: { fontSize:14, color:"#999", flex:1 },
  repLimitInput: {
    width:60, padding:"10px 12px", borderRadius:8,
    background:"#1a1a2e", border:"1px solid #444", color:"#fff",
    fontSize:15, fontWeight:700, textAlign:"center", fontFamily:"'Rajdhani',sans-serif",
  },
  repLimitUnit: { fontSize:14, color:"#666" },
  recCtrlRow: { display:"flex", gap:10 },
  recordBtn: {
    flex:1, padding:"16px 0", background:"#1a0505", border:"1px solid #ff1744",
    borderRadius:10, color:"#ff1744", fontSize:14, fontWeight:800, letterSpacing:"0.14em",
    cursor:"pointer", fontFamily:"'Rajdhani',sans-serif",
  },
  recordingActiveBtn: {
    flex:1, padding:"16px 0", background:"#ff1744", border:"1px solid #ff1744",
    borderRadius:10, color:"#fff", fontSize:14, fontWeight:800, letterSpacing:"0.14em",
    cursor:"pointer", fontFamily:"'Rajdhani',sans-serif", animation:"pulse-rec 1s infinite",
  },
  downloadBtn: {
    flex:1, padding:"16px 0", background:"#0d2818", border:"1px solid #00e676",
    borderRadius:10, color:"#00e676", fontSize:14, fontWeight:800, letterSpacing:"0.14em",
    cursor:"pointer", fontFamily:"'Rajdhani',sans-serif",
  },
  recordingStatus: {
    marginTop:14, display:"flex", alignItems:"center", gap:8,
    fontSize:14, color:"#ff1744", fontWeight:600,
  },
  recDot: {
    width:10, height:10, borderRadius:"50%", background:"#ff1744",
    animation:"pulse-rec 1s infinite",
  },
};
